# Generated by Django 3.2.4 on 2021-06-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='page_id',
            new_name='page_number',
        ),
    ]
