# Generated by Django 3.2.4 on 2021-06-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_page_id_question_page_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageQuestion',
        ),
    ]
